### PR TITLE
python implementation od demo, updated README.md

### PR DESCRIPTION
**Pull request by CS-Edwards**
- removed JS files
- added python implementation of demo
- updated README.md

@iamleonie

### CODE REVIEW

**Comment by CS-Edwards** [comment]
- added and implemented script.js for Show More button functionality
- fixed html display for additional query results
- python demo implementation is completed

**Comment by iamleonie** [comment]
Hey @CS-Edwards,
Thanks for your contribution. Due to limited capacity, reviews can take a little longer at the moment. We aim to review all PRs latest by the end of the week. Thank you for your patience.

Since this PR was created before Nov 1st, it will be Hacktoberfest eligible.

**Review by iamleonie — APPROVED** [review]
It worked like a charm. Thank you for your amazing contribution!

**Comment by iamleonie** [comment]
Related to https://github.com/weaviate-tutorials/DEMO-multimodal-text-to-image-search/issues/1

**Comment by iamleonie** [comment]
Hey @CS-Edwards,
Thank you for your contributions during Hacktoberfest 2023.
We'd like to send you some SWAG as a little thank you.
I have reached out via our Weaviate Slack for details.
Thanks again and best regards
Leonie

**Pull request merged**
